config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :employees
  resources :posts
  resources :devices
  resources :cleaning_reports
  resources :incident_reports
  resources :buildings do
    resources :floors do
      resources :wards do
        resources :rooms
      end
    end
  end
  resources :demand_reports do
    member do
      get :review
    end
  end
  resources :cleaning_requests do
    member do
      get :clean
    end
  end
  resources :inspections do
    member do
      get :inspect
    end
  end
end
  

app/models/building.rb
class Building < ApplicationRecord
  has_many :floors, dependent: :destroy
end

app/models/cleaning_report.rb
class CleaningReport < ApplicationRecord
  belongs_to :user

  after_create :clean_rooms

  def clean_rooms
    CleanRooms.call(self.room_ids, self.user_id)
  end
end

app/models/cleaning_request.rb
class CleaningRequest < ApplicationRecord
  belongs_to :user

  after_commit :generate_report, on: :update

  def generate_report
    if self.completed?
      GenerateCleaningReport.call(self.title, self.description, self.room_ids, self.user_id)
    end
  end
end

app/models/demand_report.rb
class DemandReport < ApplicationRecord
  belongs_to :user

  has_one_attached :picture

  enum status: [:awaits, :accepted, :canceled, :completed], _prefix: true

  after_initialize :set_status, :if => :new_record?

  def set_status
    self.status ||= :awaits
  end
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :room, optional: true

  has_one_attached :qr_code

  enum device_type: [:bed, :tv, :ecg, :rtg, :computer, :printer, :extinguisher, :defibrillator, :other], _prefix: true
  enum status: [:fine, :broken, :outdated, :contaminated, :other], _prefix: true

  after_create :generate_qr

  def generate_qr
    GenerateQr.call(self)
  end
end

app/models/floor.rb
class Floor < ApplicationRecord
  belongs_to :building
  has_many :wards, dependent: :destroy
end

app/models/incident_report.rb
class IncidentReport < ApplicationRecord
  belongs_to :user
end

app/models/inspection.rb
class Inspection < ApplicationRecord
  belongs_to :user
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :thumbnail
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :ward
  has_many :devices

  enum room_type: [:patients, :toilet, :storage, :office, :surgery, :post_surgery], _prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  enum role: [:inactive, :admin, :inspector, :guard, :janitor, :doctor, :nurse, :office, :technic], _prefix: true

  after_initialize :set_default_role, :if => :new_record?

  validates :name, presence: true
  validates :surname, presence: true
  
  has_many :inspections
  has_many :cleaning_requests
  has_many :posts, dependent: :destroy

  def set_default_role
    self.role ||= :inactive
  end
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :floor
  has_many :rooms, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_posts

  def index
  end

  private

  def set_posts
    if user_signed_in?
      @posts = Post.all
    else
      @posts = Post.all.where(public: true)
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button type="button" class="btn btn-dark position-relative">
    <%= link_to 'Hospital.ity',root_path, class:"navbar-brand ps-3 mb-0 h1" %>
  </button>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% if current_user.role_admin? %>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Employees', employees_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Hospital structure', buildings_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Devices', devices_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Posts', posts_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Inspections', inspections_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Incident reports', incident_reports_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Cleaning reports', cleaning_reports_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Cleaning requests', cleaning_requests_path, class:"nav-link text-light" %>
            </button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-dark position-relative">
              <%= link_to 'Demand reports', demand_reports_path, class:"nav-link text-light" %>
            </button>
          </li>
          <% else if current_user.role_office?  %>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <%= link_to 'Posts', posts_path, class:"nav-link text-light" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <%= link_to 'Inspections', inspections_path, class:"nav-link text-light" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <%= link_to 'Incident reports', incident_reports_path, class:"nav-link text-light" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <%= link_to 'Cleaning reports', cleaning_reports_path, class:"nav-link text-light" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
            <% pending_demands = DemandReport.where(status: 'awaits').count %>
            <% if pending_demands > 0 %>
              <%= link_to 'Demand reports', demand_reports_path, class:"nav-link text-light" %><span class="position-absolute top-50 start-100 translate-middle badge badge-pill bg-danger rounded-pill"><%= pending_demands.to_s %></span>
            <% else %>
              <%= link_to 'Demand reports', demand_reports_path, class:"nav-link text-light" %>
            <% end %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <%= link_to 'Devices', devices_path, class:"nav-link text-light" %>
              </button>
            </li>
          <% else if current_user.role_guard? %>
              <li class="nav-item">
                <button type="button" class="btn btn-dark position-relative">
                  <%= link_to 'Demand reports', demand_reports_path, class:"nav-link text-light" %>
                </button>
              </li>
              <li class="nav-item">
                <button type="button" class="btn btn-dark position-relative">
                  <%= link_to 'Incident reports', incident_reports_path, class:"nav-link text-light" %>
                </button>
              </li>
            <% else if current_user.role_nurse? || current_user.role_doctor?%>
                <li class="nav-item">
                  <button type="button" class="btn btn-dark position-relative">
                    <%= link_to 'Demand reports', demand_reports_path, class:"nav-link text-light" %>
                  </button>
                </li>
                <li class="nav-item">
                  <button type="button" class="btn btn-dark position-relative">
                    <%= link_to 'Cleaning requests', cleaning_requests_path, class:"nav-link text-light" %>
                  </button>
                </li>
            <% else if current_user.role_janitor? %>
                <li class="nav-item">
                  <button type="button" class="btn btn-dark position-relative">
                    <%= link_to 'Demand reports', demand_reports_path, class:"nav-link text-light" %>
                  </button>
                </li>
                <li class="nav-item">
                  <button type="button" class="btn btn-dark position-relative">
                    <%= link_to 'Cleaning reports', cleaning_reports_path, class:"nav-link text-light" %>
                  </button>
                </li>
                <li class="nav-item">
                  <button type="button" class="btn btn-dark position-relative">
                    <% pending_requests = current_user.cleaning_requests.where(completed: false).count %>
                    <% if pending_requests > 0 %>
                      <%= link_to 'Cleaning requests', cleaning_requests_path, class:"nav-link text-light" %><span class="position-absolute top-50 start-100 translate-middle badge badge-pill bg-danger rounded-pill"><%= pending_requests.to_s %></span>
                    <% else %>
                      <%= link_to 'Cleaning requests', cleaning_requests_path, class:"nav-link text-light" %>
                    <% end %>
                  </button>
                </li>
          <% else if current_user.role_inspector? || current_user.role_technic?  %>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <%= link_to 'Demand reports', demand_reports_path, class:"nav-link text-light" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <%= link_to 'Devices', devices_path, class:"nav-link text-light" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-dark position-relative">
                <% pending_inspections = current_user.inspections.where(completed: false).count %>
                <% if pending_inspections > 0 %>
                    <%= link_to 'Inspections ', inspections_path, class:"nav-link text-light" %><span class="position-absolute top-50 start-100 translate-middle badge badge-pill bg-danger rounded-pill"><%= pending_inspections.to_s %></span>
                <% else %>
                  <%= link_to 'Inspections', inspections_path, class:"nav-link text-light" %>
                <% end %>
              </button>
            </li>
          <% end %>
          <% end %>
          <% end %>
          <% end %>
        <% end %>
        <% end %>
      <% else %>
        <li class="nav-item">
          <button type="button" class="btn btn-dark position-relative">
            <%= link_to 'Log In', new_user_session_path, class:"nav-link text-light" %>
          </button>
        </li>
        <li class="nav-item">
          <button type="button" class="btn btn-dark position-relative">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link text-light" %>
          </button>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
      <li class="nav-item navbar-nav dropdown">
        <button type="button" class="btn btn-dark position-relative">

        <a class="pe-3 nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          User
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown" >
          <li class="dropdown-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"dropdown-item" %>
          </li>
          <li><hr class="dropdown-divider"></li>
          <li class="dropdown-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          </li>
        </ul>
        </button>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/_stats.html.erb
<div class="card">
  <h3 class="card-header">System statistics</h3>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <h3 class="card-header">Employees by role</h3>
          <div class="card-body">
            <%= pie_chart User.group(:role).count, donut: true, legend: "left" %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <h3 class="card-header">Devices by type</h3>
          <div class="card-body">
            <%= pie_chart Device.group(:device_type).count, donut: true, legend: "left" %>
          </div>
        </div>
      </div>
    </div><br/>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <h3 class="card-header">Reports in last week</h3>
          <div class="card-body">
            <%= column_chart [["Cleaning reports", CleaningReport.where("created_at >= ?", 1.week.ago.utc).count],
                              ["Incident reports", IncidentReport.where("created_at >= ?", 1.week.ago.utc).count],
                              ["Demand reports", DemandReport.where("created_at >= ?", 1.week.ago.utc).count]] %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <h3 class="card-header">System in numbers</h3>
          <div class="card-body text-center">
            <div class="row">

              <div class="col">
                <div class="card">
                  <h5  class="card-header alert-success">Employees</h5>
                  <div class="card-body">
                    <h1><%= User.count %></h1>
                  </div>
                </div>
              </div>

              <div class="col">
                <div class="card">
                  <h5 class="card-header alert-warning">Devices</h5>
                  <div class="card-body ">
                    <h1><%= Device.count %></h1>
                  </div>
                </div>
              </div>

              <div class="col">
                <div class="card">
                  <h5 class="card-header alert-primary">Reports</h5>
                  <div class="card-body">
                    <h1><%= CleaningReport.count + DemandReport.count + IncidentReport.count %>
                  </div>
                </div>
              </div>

              <div class="col">
                <div class="card">
                  <h5 class="card-header alert-primary">Inspections</h5>
                  <div class="card-body">
                    <h1><%= Inspection.count %></h1>
                  </div>
                </div>
              </div>

            </div><br/>
            <div class="row">

              <div class="col">
                <div class="card">
                  <h5 class="card-header alert-danger">Buildings</h5>
                  <div class="card-body">
                    <h1><%= Building.count %></h1>
                  </div>
                </div>
              </div>

              <div class="col">
                <div class="card">
                  <h5 class="card-header alert-danger">Floors</h5>
                  <div class="card-body">
                    <h1><%= Floor.count %></h1>
                  </div>
                </div>
              </div>

              <div class="col">
                <div class="card">
                  <h5 class="card-header alert-danger">Wards</h5>
                  <div class="card-body">
                    <h1><%= Ward.count %></h1>
                  </div>
                </div>
              </div>

              <div class="col">
                <div class="card danger">
                  <h5 class="card-header alert-danger">Rooms</h5>
                  <div class="card-body">
                    <h1><%= Room.count %></h1>
                  </div>
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h1>Hello <%= current_user.name %>!</h1>
  <h2>Welcome to Hospital.ity Management System.</h2>
  <% if current_user.role_inactive? %>
    <h3>Your account is deactivated, please contact system administrator.</h3>
  <% end %>
  <% if current_user.role_admin? %>
    <%= render 'stats' %>
  <% end %>
<% else %>
  <h1>Hello, please sign in or sign up to use the system.</h1>
<% end %><br/>

<br/>
<div class="card">
  <h3 class="card-header">System announcements</h3>
  <div class="card-body">
    <div class="accordion" id="accordionNews">
  <% @posts.all.order("created_at DESC").each do |post| %>
    <div class="accordion-item">
      <h2 id="heading<%= post.id %>" class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= post.id %>" aria-expanded="false" aria-controls="collapse<%= post.id %>">
          <strong><%= post.title %> | <%= post.created_at.to_s(:short  ) %></strong><br/>
        </button>
      </h2>
        <div id="collapse<%= post.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= post.id %>" data-bs-parent="#accordionNews">
        <div class="accordion-body">
          <%= post.message %><br/><br/>
          <% if post.thumbnail.attached? %>
            <%= link_to image_tag(post.thumbnail, style: 'width:30%'), post.thumbnail %><br/><br/>
          <% end %>
          <br/>
          <u><strong><%= post.user.name %> <%= post.user.surname %></strong>, <%= post.created_at.to_s(:db) %></u>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  </div>
</div><br/><br/>