config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :employees
  resources :posts
  resources :devices
  resources :cleaning_reports
  resources :incident_reports
  resources :buildings do
    resources :floors do
      resources :wards do
        resources :rooms
      end
    end
  end
  resources :demand_reports do
    member do
      get :review
    end
  end
  resources :cleaning_requests do
    member do
      get :clean
    end
  end
  resources :inspections do
    member do
      get :inspect
    end
  end
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :floors, dependent: :destroy
end

app/models/cleaning_report.rb
class CleaningReport < ApplicationRecord
  belongs_to :user

  after_create :clean_rooms

  def clean_rooms
    CleanRooms.call(self.room_ids, self.user_id)
  end
end

app/models/cleaning_request.rb
class CleaningRequest < ApplicationRecord
  belongs_to :user

  after_commit :generate_report, on: :update

  def generate_report
    if self.completed?
      GenerateCleaningReport.call(self.title, self.description, self.room_ids, self.user_id)
    end
  end
end

app/models/demand_report.rb
class DemandReport < ApplicationRecord
  belongs_to :user

  has_one_attached :picture

  enum status: [:awaits, :accepted, :canceled, :completed], _prefix: true

  after_initialize :set_status, :if => :new_record?

  def set_status
    self.status ||= :awaits
  end
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :room, optional: true

  has_one_attached :qr_code

  enum device_type: [:bed, :tv, :ecg, :rtg, :computer, :printer, :extinguisher, :defibrillator, :other], _prefix: true
  enum status: [:fine, :broken, :outdated, :contaminated, :other], _prefix: true

  after_create :generate_qr

  def generate_qr
    GenerateQr.call(self)
  end
end

app/models/floor.rb
class Floor < ApplicationRecord
  belongs_to :building
  has_many :wards, dependent: :destroy
end

app/models/incident_report.rb
class IncidentReport < ApplicationRecord
  belongs_to :user
end

app/models/inspection.rb
class Inspection < ApplicationRecord
  belongs_to :user
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :thumbnail
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :ward
  has_many :devices

  enum room_type: [:patients, :toilet, :storage, :office, :surgery, :post_surgery], _prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  enum role: [:inactive, :admin, :inspector, :guard, :janitor, :doctor, :nurse, :office, :technic], _prefix: true

  after_initialize :set_default_role, :if => :new_record?

  validates :name, presence: true
  validates :surname, presence: true
  
  has_many :inspections
  has_many :cleaning_requests
  has_many :posts, dependent: :destroy

  def set_default_role
    self.role ||= :inactive
  end
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :floor
  has_many :rooms, dependent: :destroy
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_building_and_floor
  before_action :set_ward, only: %i[ show edit update destroy ]
  before_action :correct_user
  before_action :authenticate_user!

  def index
    @q = @floor.wards.ransack(params[:q])
    @wards = @q.result(distinct: true).paginate(page: params[:page], per_page: params[:per_page])
  end

  def show
  end

  def new
    @ward = @floor.wards.new
  end

  def edit
  end

  def create
    @ward = @floor.wards.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to building_floor_ward_path(@building, @floor, @ward), notice: "Ward was successfully created." }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to building_floor_ward_path(@building, @floor, @ward), notice: "Ward was successfully updated." }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to building_floor_wards_url, notice: "Ward was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_ward
      @ward = Ward.find(params[:id])
    end

    def set_building_and_floor
      @building = Building.find(params[:building_id])
      @floor = @building.floors.find(params[:floor_id])
    end

    def ward_params
      params.require(:ward).permit(:name, :building_id, :floor_id)
    end

    def correct_user
      unless current_user.role_admin?
        redirect_to root_path, notice: "You are not authorized!"
      end
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/wards/_form.html.erb
<%= form_with model: [@building, @floor, @ward].compact, local: true do |form| %>
  <% if ward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ward.errors.count, "error") %> prohibited this ward from being saved:</h2>
      <ul>
        <% ward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div><br/>

  <div class="actions">
    <%= form.submit :Submit, class: "btn btn-outline-secondary text-dark" %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<div class="card">
  <h3 class="card-header">Edit ward</h3>
  <div class="card-body">
    <%= render 'form', ward: @ward %><br/>
    <%= link_to 'Back', building_floor_wards_path, class: "btn btn-outline-secondary text-dark" %>
    |
    <%= link_to 'Show', building_floor_ward_path(@ward), class: "btn btn-outline-secondary text-dark" %>
  </div>
</div>

app/views/wards/index.html.erb
<div class="card">
  <h3 class="card-header">Wards / <%= @floor.name %> floor / <%= @building.name %> building</h3>
    <div class="card-body">
    <%= search_form_for @q, url: building_floor_wards_path do |f| %>
      <%= f.search_field :name_cont, placeholder: "Search phrase..." %>
      <%= f.submit name: '', class: "btn btn-outline-secondary btn-sm mb-1 text-dark" %>
    <% end %>
    <br/>
    <button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to '<- Floors', building_floors_path, :class => "btn" %></button>
    <button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to 'Add Ward', new_building_floor_ward_path, :class => "btn" %></button>
    <br/><br/>
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr class="table-dark">
          <th><%= sort_link(@q, :name, "Ward name",{}, { class: "link-light" }) %></th>
          <th>Rooms</th>
        </tr>
      </thead>
      <tbody>
        <% @wards.each do |ward| %>
          <tr>
            <td><button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to ward.name, building_floor_ward_path(@building, @floor, ward), :class => "btn" %></button></td>
            <td><button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to ward.rooms.count, building_floor_ward_rooms_path(@building, @floor, ward), :class => "btn" %></button></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/wards/new.html.erb
<div class="card">
  <h3 class="card-header">New ward / <%= @floor.name %> floor / <%= @building.name %> building</h3>
  <div class="card-body">
    <%= render 'form', ward: @ward %>
    <br/>
    <%= link_to 'Back', building_floor_wards_path, class: "btn btn-outline-secondary text-dark" %>
  </div>
</div>

app/views/wards/show.html.erb
<div class="card">
  <h3 class="card-header">Ward details</h3>
  <div class="card-body">
    <p>
      <strong>Ward name:</strong>
      <%= @ward.name %>
    </p>
    <p>
      <strong>Rooms count:</strong>
      <%= @ward.rooms.count %>
    </p>
    <p>
      <strong>Ward location:</strong>
      Building <%= @ward.floor.building.name %> / <%= @ward.floor.name %> floor
    </p>

    <%= link_to 'Back', building_floor_wards_path, class: "btn btn-outline-secondary text-dark" %> |
    <%= link_to 'Edit', edit_building_floor_ward_path(@building, @floor, @ward), class: "btn btn-outline-secondary text-dark" %>
  </div>
</div>