config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :employees
  resources :posts
  resources :devices
  resources :cleaning_reports
  resources :incident_reports
  resources :buildings do
    resources :floors do
      resources :wards do
        resources :rooms
      end
    end
  end
  resources :demand_reports do
    member do
      get :review
    end
  end
  resources :cleaning_requests do
    member do
      get :clean
    end
  end
  resources :inspections do
    member do
      get :inspect
    end
  end
end
  

app/models/building.rb
class Building < ApplicationRecord
  has_many :floors, dependent: :destroy
end

app/models/cleaning_report.rb
class CleaningReport < ApplicationRecord
  belongs_to :user

  after_create :clean_rooms

  def clean_rooms
    CleanRooms.call(self.room_ids, self.user_id)
  end
end

app/models/cleaning_request.rb
class CleaningRequest < ApplicationRecord
  belongs_to :user

  after_commit :generate_report, on: :update

  def generate_report
    if self.completed?
      GenerateCleaningReport.call(self.title, self.description, self.room_ids, self.user_id)
    end
  end
end

app/models/demand_report.rb
class DemandReport < ApplicationRecord
  belongs_to :user

  has_one_attached :picture

  enum status: [:awaits, :accepted, :canceled, :completed], _prefix: true

  after_initialize :set_status, :if => :new_record?

  def set_status
    self.status ||= :awaits
  end
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :room, optional: true

  has_one_attached :qr_code

  enum device_type: [:bed, :tv, :ecg, :rtg, :computer, :printer, :extinguisher, :defibrillator, :other], _prefix: true
  enum status: [:fine, :broken, :outdated, :contaminated, :other], _prefix: true

  after_create :generate_qr

  def generate_qr
    GenerateQr.call(self)
  end
end

app/models/floor.rb
class Floor < ApplicationRecord
  belongs_to :building
  has_many :wards, dependent: :destroy
end

app/models/incident_report.rb
class IncidentReport < ApplicationRecord
  belongs_to :user
end

app/models/inspection.rb
class Inspection < ApplicationRecord
  belongs_to :user
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :thumbnail
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :ward
  has_many :devices

  enum room_type: [:patients, :toilet, :storage, :office, :surgery, :post_surgery], _prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  enum role: [:inactive, :admin, :inspector, :guard, :janitor, :doctor, :nurse, :office, :technic], _prefix: true

  after_initialize :set_default_role, :if => :new_record?

  validates :name, presence: true
  validates :surname, presence: true
  
  has_many :inspections
  has_many :cleaning_requests
  has_many :posts, dependent: :destroy

  def set_default_role
    self.role ||= :inactive
  end
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :floor
  has_many :rooms, dependent: :destroy
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_inspection, only: %i[ show edit update destroy inspect ]

  def index
    if current_user.role_technic? || current_user.role_inspector?
      @q = Inspection.all.where(user_id: current_user.id).ransack(params[:q])
    else
      @q = Inspection.all.ransack(params[:q])
    end
    @inspections = @q.result(distinct: true).paginate(page: params[:page], per_page: params[:per_page])
  end

  def show
  end

  def new
    @inspection = Inspection.new
  end

  def edit
  end

  def inspect
  end

  def create
    @inspection = Inspection.new(inspection_params)

    respond_to do |format|
      if @inspection.save
        format.html { redirect_to @inspection, notice: "Inspection was successfully created." }
        format.json { render :show, status: :created, location: @inspection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: "Inspection was successfully updated." }
        format.json { render :show, status: :ok, location: @inspection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inspection.destroy
    respond_to do |format|
      format.html { redirect_to inspections_url, notice: "Inspection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_inspection
      @inspection = Inspection.find(params[:id])
    end

    def inspection_params
      params.require(:inspection).permit(:title, :description, :user_id, :completed, :notes, :device_ids => [])
    end

  def correct_user
    unless current_user.role_admin? || current_user.role_office? || current_user.role_technic? || current_user.role_inspector?
      redirect_to root_path, notice: "You are not authorized!"
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/inspections/_device.html.erb
<p>
  <strong>Model:</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @device.manufacturer %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @device.serial_number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @device.device_type %>
</p>

<p>
  <strong>Device status:</strong>
  <%= @device.status %>
</p>

<p>
  <strong>Location:</strong>
  <% if @device.room.present? %>
    Room <%= @device.room.name %> / <%= @device.room.ward.name %> ward / <%= @device.room.ward.floor.name %> floor / <%= @device.room.ward.floor.building.name %> building
  <% else %>
    Hospital storage
  <% end %>
</p><br/>

app/views/inspections/_form.html.erb
<%= form_with(model: inspection) do |form| %>
  <% if inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
        <% inspection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div><br/>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div><br/>

  <div class="field">
    <%= form.label :devices , "Select devices for inspection"%>
    <div class="accordion" id="accordionWards">
      <% Ward.all.each do |ward| %>
        <div class="accordion-item">
          <h2 id="heading-ward<%= ward.id %>" class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ward<%= ward.id %>" aria-expanded="false" aria-controls="collapse-ward<%= ward.id %>">
              <strong><%= ward.name %> ward</strong><br/>
            </button>
          </h2>
          <div id="collapse-ward<%= ward.id %>" class="accordion-collapse collapse" aria-labelledby="heading-ward<%= ward.id %>" data-bs-parent="#accordionWards">
            <div class="accordion-body">
              <div class="accordion" id="accordionRooms-ward<%= ward.id %>">
                <% ward.rooms.each do |room| %>
                  <% if room.devices.count > 0 %>
                  <div class="accordion-item">
                    <h2 id="heading-room<%= room.id %>" class="accordion-header">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-room<%= room.id %>" aria-expanded="false" aria-controls="collapse-room<%= room.id %>">
                        <strong>Room <%= room.name %> | <%= room.room_type %></strong><br/>
                      </button>
                    </h2>
                    <div id="collapse-room<%= room.id %>" class="accordion-collapse collapse" aria-labelledby="heading-room<%= room.id %>" data-bs-parent="#accordionRooms-ward<%= ward.id %>">
                      <div class="accordion-body">
                        <span class="ul">
                          <% room.devices.each do |device| %>
                            <label class="li"><%= check_box_tag :device_ids, device.id, false, :name => 'inspection[device_ids][]' %> <strong><%= device.name %> | <%= device.serial_number %> | <%= device.device_type %> | <%= device.status %></strong></label><br />
                          <% end %>
                        </span>
                      </div>
                    </div>
                  </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="accordion-item">
        <h2 id="heading" class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse" aria-expanded="false" aria-controls="collapse">
            <strong>Hospital storage</strong><br/>
          </button>
        </h2>
        <div id="collapse" class="accordion-collapse collapse" aria-labelledby="heading" data-bs-parent="#accordionWards">
          <div class="accordion-body">
            <span class="ul">
              <% Device.all.where(room_id: nil).each do |device| %>
                <label class="li"><%= check_box_tag :device_ids, device.id, false, :name => 'inspection[device_ids][]' %> <strong><%= device.name %> | <%= device.serial_number %> | <%= device.device_type %> | <%= device.status %></strong></label><br/>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div><br/>

  <div class="field">
    <% grouped_options_for_select = [['Inspectors', User.all.where(role: "inspector").collect {|u| [ u.name + " " + u.surname, u.id ] }]] %>
    <% grouped_options_for_select << ['Technicians', User.all.where(role: "technic").collect {|u| [ u.name + " " + u.surname, u.id ] }] %>
    <%= form.label :user_id, "Employee delegated:" %>
    <%= form.select :user_id, grouped_options_for_select(grouped_options_for_select), {}, {class: "form-control form-select mb-3"} %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class: "btn btn-outline-secondary text-dark" %>
  </div>
<% end %>

app/views/inspections/_inspector_form.html.erb
<%= form_with(model: inspection) do |form| %>
  <% if inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>›
      <ul>
        <% inspection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Title:</strong>
    <%= @inspection.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @inspection.description %>
  </p>

  <div class="field">
    <strong>Devices to inspect:</strong>
    <div class="accordion" id="accordionWards">
      <% devices = Device.all.where(id: @inspection.device_ids) %>
      <% counter = 1 %>
      <% devices.each do |device| %>
        <div class="accordion-item">
          <h2 id="heading-ward<%= device.id %>" class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-ward<%= device.id %>" aria-expanded="false" aria-controls="collapse-ward<%= device.id %>">
              <strong><%= counter %>. Device - <%= device.name %></strong><br/>
            </button>
          </h2>
          <div id="collapse-ward<%= device.id %>" class="accordion-collapse collapse" aria-labelledby="heading-ward<%= device.id %>" data-bs-parent="#accordionWards">
            <div class="accordion-body">
              <% @device = device %>
              <%= render 'device', device: @device %>
              <label class="li"><%= check_box_tag :device_ids, device.id, false, :required => true, :name => 'inspection[device_ids][]' %> <strong>Inspected</strong></label><br/>
            </div>
          </div>
        </div>
        <% counter += 1 %>
    <% end %>
    </div>
  </div><br/>

  <div class="field form-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, class: "form-control" %>
  </div><br/>

  <div class="field">
    <%= form.hidden_field :completed, value: true %>
  </div>

  <div class="actions">
    <%= form.submit "Finish inspection", class: "btn btn-outline-secondary text-dark" %>
  </div>
<% end %>

app/views/inspections/edit.html.erb
<div class="card">
  <h3 class="card-header">Edit Inspection</h3>
  <div class="card-body">
    <%= render 'form', inspection: @inspection %>
    <br/>
    <%= link_to 'Back', inspections_path, class: "btn btn-outline-secondary text-dark" %>
    |
    <%= link_to 'Show', @inspection, class: "btn btn-outline-secondary text-dark" %>
  </div>
</div>

app/views/inspections/index.html.erb
<div class="card">
  <h3 class="card-header">Inspections</h3>
  <div class="card-body">
    <%= search_form_for @q, url: inspections_path do |f| %>
      <%= f.search_field :title_or_description_cont, placeholder: "Search phrase..." %>
      <%= f.select :completed_eq, options_for_select([
                                                          ['Any state...', ''],
                                                         ['Completed', true],
                                                         ['Not completed', false]
                                                       ])%>
      <%= f.submit name: '', class: "btn btn-outline-secondary btn-sm mb-1 text-dark" %>
    <% end %>
    <br/>
    <% unless current_user.role_technic? || current_user.role_inspector?%>
    <button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to 'New inspection', new_inspection_path, :class => "btn" %></button>
    <br/><br/>
    <% end %>
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr class="table-dark">
          <th><%= sort_link(@q, :title, "Title",{}, { class: "link-light" }) %></th>
          <% unless current_user.role_technic? || current_user.role_inspector?%>
            <th><%= sort_link(@q, :user_id, "Assigned employee",{}, { class: "link-light" }) %></th>
          <% end %>
          <th><%= sort_link(@q, :created_at, "Comissioned on",{}, { class: "link-light" }) %></th>
          <th><%= sort_link(@q, :completed, "Completed",{}, { class: "link-light" }) %></th>
          <th><%= sort_link(@q, :created_at, "Completed on",{}, { class: "link-light" }) %></th>
        </tr>
      </thead>
      <tbody>
        <% @inspections.each do |inspection| %>
          <tr>
            <% if current_user.role_technic? || current_user.role_inspector?%>
              <% if inspection.completed? %>
                <td><button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to inspection.title, inspect_inspection_path(inspection), :class => "btn disabled" %></button></td>
                <% else %>
                <td><button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to inspection.title, inspect_inspection_path(inspection), :class => "btn" %></button></td>
              <% end %>
            <% else %>
              <td><button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to inspection.title, inspection, :class => "btn" %></button></td>
              <td><%= inspection.user.name + ' ' + inspection.user.surname %></td>
            <% end %>
            <td><%= inspection.created_at.to_s(:db) %></td>
            <td><%= inspection.completed %></td>
            <td>
              <% if inspection.completed? %>
                <%= inspection.updated_at.to_s(:db) %>
              <% else %>
                -
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/inspections/inspect.html.erb
<div class="card">
  <h3 class="card-header">Execute Inspection</h3>
  <div class="card-body">
    <%= render 'inspector_form', inspection: @inspection %>
    <br/>
    <%= link_to 'Back', inspections_path, class: "btn btn-outline-secondary text-dark" %>
  </div>
</div>

app/views/inspections/new.html.erb
<div class="card">
  <h3 class="card-header">New inspection</h3>
  <div class="card-body">
    <%= render 'form', inspection: @inspection %>
    <br/>
    <%= link_to 'Back', inspections_path, class: "btn btn-outline-secondary text-dark" %>
  </div>
</div>

app/views/inspections/show.html.erb
<div class="card">
  <h3 class="card-header">Inspection</h3>
  <div class="card-body">
    <p>
      <strong>Title:</strong>
      <%= @inspection.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @inspection.description %>
    </p>

    <p>
      <strong>Delegated employee:</strong>
      <%= @inspection.user.name %> <%= @inspection.user.surname %>
    </p>

    <p>
      <strong>Devices to inspect:</strong>
      <ol>
        <% devices = Device.all.where(id: @inspection.device_ids) %>
        <% devices.each do |device| %>
        <li>
          <%= device.name %> | <% device.model %> |
          <% if device.room.present? %>
            Room <%= device.room.name %> / <%= device.room.ward.name %> ward / <%= device.room.ward.floor.name %> floor / <%= device.room.ward.floor.building.name %> building
          <% else %>
            Hospital storage
          <% end %>
        <% end %>
        </li>
      </ol>
    </p>

    <p>
      <strong>Completed:</strong>
      <%= @inspection.completed %>
    </p>
    <% if @inspection.completed? %>
    <p>
      <strong>Inspection results:</strong>
      <%= @inspection.notes %>
    </p>
    <% end %>
    <% unless current_user.role_technic? || current_user.role_inspector?%>
      <%= link_to 'Back', inspections_path, class: "btn btn-outline-secondary text-dark" %> |
      <%= link_to 'Edit', edit_inspection_path(@inspection), class: "btn btn-outline-secondary text-dark" %> <br/><br/>
      <%= button_to 'Delete', inspection_path(@inspection), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger text-light" %>
    <% else %>
      <%= link_to 'Back', inspections_path, class: "btn btn-outline-secondary text-dark" %><br/><br/>
  <% end %>
  </div>
</div>